# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f58d2ee2181c120f6c89154c153d94554df3fdfce65840d7f592606122dc594de19a53b5ebd4072e9a24b13575c629d5d09aada0d30f60ab2f51843dedb2c1ae

test:
  secret_key_base: ce5717cc9afdc1c8289b5fc19c60c0a593173dded3e90cdeb65bda847d2a40929c53f663d0ac873505b31edb0a98df6a35fffde75ae18f38a81b3ccd65c623a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
